[tox]
envlist =
    # linters
    ruff
    pylint
    mypy
    # unit tests
    py{311,312,313,314}

[testenv]
commands =
    {envpython} -m unittest discover -v -s tests -p "test_*.py" {posargs:-b}
deps =
    httpx2
setenv =
    PYTHONDONTWRITEBYTECODE=1
usedevelop =
    true

[testenv:coverage]
deps =
    {[testenv]deps}
    coverage
commands =
    {envpython} -m coverage run --module unittest discover -b -s tests -p "test_*.py" {posargs}
    - {envpython} -m coverage combine
    {envpython} -m coverage html
    {envpython} -m coverage report

[testenv:httpd]
deps =
commands =
    uvicorn sphinx_confluence_relay.main:app --reload --host 127.0.0.1 --port 29981
passenv =
    *

[testenv:mypy]
deps =
    mypy: mypy==2.3.0
setenv =
    {[testenv]setenv}
    MYPY_CACHE_DIR={toxworkdir}/.mypy_cache
commands =
    mypy \
    sphinx_confluence_relay

[testenv:pylint]
deps =
    pylint: pylint==4.0.6
setenv =
    {[testenv]setenv}
    MYPY_CACHE_DIR={toxworkdir}/.mypy_cache
commands =
    pylint \
    sphinx_confluence_relay \
    tests

[testenv:ruff]
deps =
    ruff: ruff==0.15.22
setenv =
    {[testenv]setenv}
    RUFF_CACHE_DIR={toxworkdir}/.ruff_cache
commands =
    ruff \
    check \
    sphinx_confluence_relay \
    tests
